import type { Event } from "@/types/event";

export const MOCK_EVENTS: Event[] = [
    {
        id: "1",
        name: "React Native Budapest Meetup",
        location: "BME I Building, Budapest",
        country: "Hungary",
        capacity: 120,
    },
    {
        id: "2",
        name: "Frontend Conference 2026",
        location: "Müpa Budapest",
        country: "Hungary",
        capacity: 450,
    },
    {
        id: "3",
        name: "TypeScript Deep Dive Workshop",
        location: "Impact Hub Budapest",
        country: "Hungary",
        capacity: 40,
    },
    {
        id: "4",
        name: "Mobile Dev Hack Night",
        location: "Kitchen Budapest",
        country: "Hungary",
        capacity: 60,
    },
    {
        id: "5",
        name: "UX Design Sprint",
        location: "Design Terminal",
        country: "Hungary",
    },
    {
        id: "6",
        name: "Cloud Native Summit",
        location: "MOM Cultural Center",
        country: "Hungary",
        capacity: 300,
    },
    {
        id: "7",
        name: "Product Management Roundtable",
        location: "Kálvin Square Office Hub",
        country: "Hungary",
        capacity: 25,
    },
    {
        id: "8",
        name: "JavaScript Open Mic",
        location: "Loffice Budapest",
        country: "Hungary",
        capacity: 80,
    },
    {
        id: "9",
        name: "AI in Production",
        location: "Corvinus University",
        country: "Hungary",
        capacity: 200,
    },
    {
        id: "10",
        name: "Startup Pitch Day",
        location: "BudaPart Innovation Park",
        country: "Hungary",
        capacity: 150,
    },
    {
        id: "11",
        name: "Women in Tech Breakfast",
        location: "Brody House",
        country: "Hungary",
        capacity: 50,
    },
    {
        id: "12",
        name: "GraphQL Community Day",
        location: "Prezi HQ",
        country: "Hungary",
        capacity: 100,
    },
    {
        id: "13",
        name: "Accessibility First Meetup",
        location: "Central European University",
        country: "Hungary",
        capacity: 70,
    },
    {
        id: "14",
        name: "DevOps Live Demo",
        location: "Infopark Building C",
        country: "Hungary",
        capacity: 90,
    },
    {
        id: "15",
        name: "Kotlin Multiplatform Talk",
        location: "Etele Plaza Conference Room",
        country: "Hungary",
    },
    {
        id: "16",
        name: "Open Source Contributors Night",
        location: "Google Developer Space",
        country: "Hungary",
        capacity: 110,
    },
    {
        id: "17",
        name: "Cybersecurity Essentials",
        location: "National University of Public Service",
        country: "Hungary",
        capacity: 180,
    },
    {
        id: "18",
        name: "Agile Retrospective Workshop",
        location: "Aqua Budapest",
        country: "Hungary",
        capacity: 35,
    },
    {
        id: "19",
        name: "Data Engineering Meetup",
        location: "Graphisoft Park",
        country: "Hungary",
        capacity: 95,
    },
    {
        id: "20",
        name: "iOS Developers Hungary",
        location: "Apple Developer Academy",
        country: "Hungary",
        capacity: 75,
    },
    {
        id: "21",
        name: "Web Performance Clinic",
        location: "Szimpla Kert Garden",
        country: "Hungary",
        capacity: 55,
    },
    {
        id: "22",
        name: "Green Tech Forum",
        location: "Millenaris Park",
        country: "Hungary",
        capacity: 250,
    },
    {
        id: "23",
        name: "Junior Dev Career Panel",
        location: "Codecool Campus",
        country: "Hungary",
        capacity: 65,
    },
    {
        id: "24",
        name: "Remote Work Best Practices",
        location: "Online",
        capacity: 500,
    },
    {
        id: "25",
        name: "API Design Masterclass",
        location: "Danube Palace",
        country: "Hungary",
        capacity: 85,
    },
    {
        id: "26",
        name: "Flutter Hungary Meetup",
        location: "ELTE Lágymányos Campus",
        country: "Hungary",
        capacity: 130,
    },
    {
        id: "27",
        name: "Tech Leadership Summit",
        location: "Kempinski Hotel Corvinus",
        country: "Hungary",
        capacity: 220,
    },
    {
        id: "28",
        name: "Local Community BBQ",
        location: "Margitsziget Picnic Area",
        country: "Hungary",
    },
    {
        id: "29",
        name: "Testing Strategies Workshop",
        location: "Green Fox Academy",
        country: "Hungary",
        capacity: 45,
    },
    {
        id: "30",
        name: "Year-End Developer Party",
        location: "A38 Ship",
        country: "Hungary",
        capacity: 400,
    },
];
